lang: en_US

mysql:
  enable: false
  host: "localhost"
  port: 3306
  user: "root"
  pass: ""
  database: "server"

menus:
  market:
    background: GRAY_STAINED_GLASS_PANE
    border: BLACK_STAINED_GLASS_PANE
    next:
      type: PAPER
      slot: 53
    previous:
      type: PAPER
      slot: 46
    close:
      type: ARROW
      slot: 49
    order:
      type: BOOK
      slot: 51
    info:
      type: REDSTONE_TORCH_ON
      slot: 50
    storage:
      type: CHEST
      slot: 52
    categories:
      all:
        type: NETHER_STAR
      ores:
        type: IRON_PICKAXE
      potions:
        type: POTION
      redstone:
        type: REDSTONE
      tools:
        type: FISHING_ROD
      wood:
        type: IRON_AXE
  storage:
    background: GRAY_STAINED_GLASS_PANE
    border: BLACK_STAINED_GLASS_PANE
    back:
      type: ARROW
      slot: 49
    take_items:
      type: NETHER_STAR
      slot: 50

minimum_price: 1.0
taxes: 7 # percent

limit: 5 # items by user
expired_time: 1440 # 1440 minutes = 24 hours

blacklist_enable: false

sell_alias:
- sell