lang: en_US

mysql:
  enable: false
  host: "localhost"
  port: 3306
  user: "root"
  pass: ""
  database: "server"

menus:
  market: # You can use custom models like this -> material#custom_model_id - GRAY_STAINED_GLASS_PANE#2200002
    background: GRAY_STAINED_GLASS_PANE
    border: BLACK_STAINED_GLASS_PANE
    sales:
      type: NETHER_STAR
      slot: 47
    next:
      type: PAPER
      slot: 53
    previous:
      type: PAPER
      slot: 46
    close:
      type: ARROW
      slot: 49
    order:
      type: BOOK
      slot: 51
    info:
      type: REDSTONE_TORCH_ON
      slot: 50
    storage:
      type: CHEST
      slot: 52
    categories:
      all:
        type: NETHER_STAR
      ores:
        type: IRON_PICKAXE
      potions:
        type: POTION
      redstone:
        type: REDSTONE
      tools:
        type: FISHING_ROD
      wood:
        type: IRON_AXE
  storage:
    background: GRAY_STAINED_GLASS_PANE
    border: BLACK_STAINED_GLASS_PANE
    back:
      type: ARROW
      slot: 49
    take_items:
      type: NETHER_STAR
      slot: 50
  sales:
    background: GRAY_STAINED_GLASS_PANE
    border: BLACK_STAINED_GLASS_PANE
    back:
      type: ARROW
      slot: 49
    item:
      type: DIAMOND_SWORD
      slot: 20
    value:
      type: SUNFLOWER
      slot: 24
    post:
      type: EMERALD
      slot: 22
  content:
    border: BLACK_STAINED_GLASS_PANE
    back:
      type: ARROW
      slot: 49
  confirm:
    background: GRAY_STAINED_GLASS_PANE
    border: BLACK_STAINED_GLASS_PANE
    back:
      type: ARROW
      slot: 49
    buy:
      type: EMERALD
      slot: 20
    cancel:
      type: BARRIER
      slot: 24
    item:
      slot: 22

minimum_price: 1.0
taxes: 7 # percent

limit: 5 # items by user
expired_time: 1440 # 1440 minutes = 24 hours

blacklist_enable: false
blacklistlore_enable: false

confirm_menu_enable: false

sell_alias:
- sell