
npc_list: 

order: 
   format: "%active% %value%"
   active: "&cÂ»&4"
   values:
      id: "IDs"
      type: "Material"
      amount: "Amount"
      value: "Value"

taxes: 7 # percent

limit: 5 # items by user
expired_time: 1440 # 1440 minutes = 24 hours

item_onsale:
- "&8Owner: &b%owner%"
- "&8Value: &6%value%$"
- "&8To expire: &b%expired%"
- ""
- "&eClick to buy!"

items:
   next:
      type: PAPER
      name: "&eNext page (%actual_page%-%pages%)"
   previous:
      type: PAPER
      name: "&ePrevious page (%actual_page%-%pages%)"
   close:
      type: ARROW
      name: "&cExit"
   back:
      type: ARROW
      name: "&cReturn"
   order_type:
      type: BOOK
      name: "&bOrder type"
      lore:
      - "&8- &7%order_id%"
      - "&8- &7%order_type%"
      - "&8- &7%order_amount%"
      - "&8- &7%order_value%"
      - ""
      - "&eClick to change!"
   info:
      type: REDSTONE_TORCH_ON
      name: "&bInformation"
      lore:
      - "&7Cmd to sold /sell <amount>"
      - "&4(Time to expired 24 hours)"
   storage:
      type: CHEST
      name: "&bStorage"
      lore:
      - "&7Your unsold items"
      - ""
      - "&eClick to open!"